"""
Generate signing secrets and write them to backend/.env

The values shipped in config.py are published in the source, so anyone holding
a copy of this repository can forge an administrator token. This replaces them
with values from the operating system's cryptographic random source.

    python scripts/generate_secrets.py            # create .env if absent
    python scripts/generate_secrets.py --rotate   # replace existing secrets

Rotating invalidates every issued token, so all users must sign in again.
"""

import argparse
import os
import re
import secrets
import sys

BACKEND_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ENV_PATH = os.path.join(BACKEND_DIR, ".env")

MANAGED_KEYS = ("SECRET_KEY", "JWT_SECRET")

TEMPLATE = """# Local configuration. Never commit this file.
# Generated by scripts/generate_secrets.py

SECRET_KEY={secret_key}
JWT_SECRET={jwt_secret}

# Set False for anything reachable beyond localhost. With DEBUG=False the
# application refuses to start on placeholder secrets rather than running
# insecurely.
DEBUG=True

# ── Optional integrations ────────────────────────────────────────────
# Telegram full API (my.telegram.org). Without these only the public
# web-preview scraper is available.
# TELEGRAM_API_ID=
# TELEGRAM_API_HASH=

# Tor, for .onion collection. Requires a running Tor daemon.
# TOR_ENABLED=True

# Neo4j, if you prefer it to the built-in graph tables.
# NEO4J_ENABLED=True
# NEO4J_PASSWORD=
"""


def generate() -> dict:
    return {
        "secret_key": secrets.token_hex(32),
        "jwt_secret": secrets.token_hex(32),
    }


def rotate_existing(content: str, values: dict) -> str:
    """Replace managed keys in place, preserving everything else."""
    replacements = {"SECRET_KEY": values["secret_key"],
                    "JWT_SECRET": values["jwt_secret"]}
    for key, value in replacements.items():
        pattern = re.compile(rf"^{key}=.*$", re.MULTILINE)
        if pattern.search(content):
            content = pattern.sub(f"{key}={value}", content)
        else:
            content = content.rstrip() + f"\n{key}={value}\n"
    return content


def main(rotate: bool) -> int:
    values = generate()

    if os.path.exists(ENV_PATH) and not rotate:
        print(f".env already exists at {ENV_PATH}")
        print("Nothing written. Use --rotate to replace the existing secrets")
        print("(this invalidates every issued token; users must sign in again).")
        return 1

    if os.path.exists(ENV_PATH):
        with open(ENV_PATH, encoding="utf-8") as f:
            content = rotate_existing(f.read(), values)
        action = "Rotated secrets in"
    else:
        content = TEMPLATE.format(**values)
        action = "Created"

    with open(ENV_PATH, "w", encoding="utf-8") as f:
        f.write(content)

    # Best effort on Windows, which ignores chmod for most purposes.
    try:
        os.chmod(ENV_PATH, 0o600)
    except OSError:
        pass

    print(f"{action} {ENV_PATH}")
    print("  SECRET_KEY  set (64 hex characters)")
    print("  JWT_SECRET  set (64 hex characters)")
    print()
    print("Confirm .env is git-ignored before committing anything.")
    if rotate:
        print("Existing tokens are now invalid; all users must sign in again.")
    return 0


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--rotate", action="store_true",
                        help="replace secrets in an existing .env")
    sys.exit(main(parser.parse_args().rotate))
